name: Deploy my lambda function

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout out code
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Install libraries
        run: |
            cd function
            python -m pip install -upgrade pip
            if [ -f requeriments.txt ]: then pip install -r requeriments.txt -t .; fi
      - name: Create zip bundle
        run: |
          cd function
          zip -r ../${{ github.sha }}.zip .
      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
            
